---
:verbose: true 
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 25
:timeout: 30
:queues:
  - [crawler, 5]
  - [default, 7]
  - [seasons, 4]
  - [yts, 5]
  - [movie, 3]
  - [file_size, 3]
  - [tv, 5]
  - [similar_movies, 2]
